defaultAppearance = "dark"
colorScheme = "ocean"
defaultBackgroundImage = "."
enableSearch = false

[homepage]
layout = "profile"
showRecent = ""
homepageImage = "."
layoutBackgroundBlur = true

[header]
layout = "basic"
