baseURL = "https://tdubiel.dev"
languageCode = "en-us"
title = "Tomasz Dubiel"
theme = "minimal"
disqusShortname = ""
googleAnalytics = ""

[params]
    author = "Tomasz Dubiel"
    description = "Software friend"
    githubUsername = "tmpdubz"
    accent = "salmon"
    showBorder = true
    backgroundColor = "snow"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "scala", "javascript", "bash"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    name = "CV"
    url = "/resume/"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:t.m.dubiel@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/tmpdubz/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/tmpdubz/"
    name = "fab fa-linkedin"
    weight = 3
